SELECT DISTINCT CONCAT(E.Fname, " ", Minit, " ", Lname), Ssn, Dno, Dname
FROM EMPLOYEE E, (SELECT Mgr_ssn, Dname, Dnumber from DEPARTMENT WHERE Dnumber IN(SELECT DISTINCT Dno FROM EMPLOYEE WHERE Ssn IN(SELECT DISTINCT Essn FROM WORKS_ON GROUP BY Essn HAVING SUM(Hours) < 40.0))) AS D
WHERE E.Ssn = D.Mgr_ssn;
